### PR TITLE
adds pairs metatable for GVariant dictionary

### PR DESCRIPTION
**Pull request by terminar**
This is a possible fix for https://github.com/pavouk/lgi/issues/201

### CODE REVIEW

**Comment by psychon** [comment]
I haven't tested this, but from a quick first look it seems sane.
Could you also add a unit test for this? Something similar to my answers in #201: The code constructs a `GVariant`-instance and then tests that iterating over it produces the expected values.
(The test can be wrapped in either `if _VERSION >= "5.1"` or (perhaps better) some feature test, e.g. `if 42 == pairs(setmetatable({}, { __pairs = function() return 42 end })) then`)

Side note: I'll be offline for a while soon-ish.

**Comment by terminar** [comment]
Regarding _VERSION: 
That maybe needs some discussion. I thought about _VERSION check but that adds unnecessary complexity (and useless code).
If it's Lua < 5.2 or Luajit then __pairs metamethod is just ignored and should never called. If it's compatible with __pairs, it's just called. That's the current situation which doesn't produce errors.

A better idea is maybe adding a custom iterator method (which uses __pairs metamethod if defined also in 5.1) somewhere in the lgi which can be called instead of pairs(). Also we can replace pairs() with that compatibility version - but then we will maybe harm the performance of the code and change how foreign Lua code works. I'm not sure if it's really useful to do such compatibility stuff (even checking for _VERSION). What's your opinion?

Regarding tests: I'll put a new commit onto the MR with a working test, give me some minutes.

**Comment by psychon** [comment]
I only meant "a version check for the test", not for the code itself. The test definitely this check since it otherwise fails with Lua 5.1.

**Comment by terminar** [comment]
Ah, understood. Your test with 42 should work for Lua 5.1 - everything that doesn't support __pairs should not return 42 :)

I added two tests, because there are two different situations.
1. function variant.pairs_on_variant_returned_dict
That's my test case from #201. 
If a Variant tuple is used, the override-magic from Glib-Variant.Lua ~223 is used.
It returns the extracted data as value in Line 230 (get_variant(var.value[2])) as part of the Lua table (due to the call to tup.value[2] - the access to ".value" does the convert magic)

2. function variant.pairs_on_variant
Your example on a Variant. Due to the fact that the variant itself is a userdata, pairs() is not working.
It is possible to extend the Variant metatable (I tried that) with
```
local vmt = getmetatable(Variant)
vmt.__pairs = pairs
```
but then, pairs() is still not working because of the userdatba-type. If I also extend
```
vmt.__metatable = { __ index = function(tbl,key) return rawget(Variant,key) end }
```
pairs() is working but the rest of the Variant code breaks completely, so that's not possible with small code changes. I think it should be possible to extend the Variant userdata itself to support __pairs, but that's too deep for today and this merge request :)

Both tests were successful here.

**Pull request merged**
