### PR TITLE
A little contribution to the LGI documentation

### PR DESCRIPTION
**Pull request by M1que4s**
I had this pending for a while. I want to help with documentation, so hopefully this can help a little. The example repository I added is still in process, but it is active.

### CODE REVIEW

**Review by psychon — APPROVED** [review]
After looking a bit at the examples: I now believe you know more about LGI + GTK than I do.

(I'm just approving it to give others at least a chance to complain about this. Feel free to ping me in a week or so if no one complained. I don't know why anyone would complain...)

**Comment by M1que4s** [comment]
> After looking a bit at the examples: I now believe you know more about LGI + GTK than I do.

Thanks a lot bro!

> (I'm just approving it to give others at least a chance to complain about this. Feel free to ping me in a week or so if no one complained. I don't know why anyone would complain...)

I'll try to be aware if anything happens.

**Comment by diazvictor** [comment]
excellent contribution, I take this opportunity to comment on the possibility of a wiki.I would be willing to collaborate in the creation of this one.

**Comment by M1que4s** [comment]
> excellent contribution, I take this opportunity to comment on the possibility of a wiki.I would be willing to collaborate in the creation of this one.

@psychon that's sound good!

**Comment by sodomon2** [comment]
> I had this pending for a while. I want to help with documentation, so hopefully this can help a little. The example repository I added is still in process, but it is active.

Excellent contribution, It will help me a lot, I hope you keep it active, as there is a lot to do.

> excellent contribution, I take this opportunity to comment on the possibility of a wiki.I would be willing to collaborate in the creation of this one.

It would be a great help. Many times I get caught up in the pygobject documentation to look for information as there are many things that are not in the lgi documentation. If this happens to me it is very likely that many others have the same thing happening to them.

**Comment by M1que4s** [comment]
> It would be a great help. Many times I get caught up in the pygobject documentation to look for information as there are many things that are not in the lgi documentation. If this happens to me it is very likely that many others have the same thing happening to them.

You are correct. It is necessary to improve the LGI documentation because the GI based bindings, in terms of API are all very similar, but at the programming language level for which they are made, they usually have slight differences (mostly because they are language specific details).

> Excellent contribution, It will help me a lot, I hope you keep it active, as there is a lot to do.

Yes, I try to add examples in a certain order thinking mainly for those who are new to LGI/Gtk.

**Comment by psychon** [comment]
Okay, that was quick and quite positive. Nice. :-)

>> excellent contribution, I take this opportunity to comment on the possibility of a wiki.I would be willing to collaborate in the creation of this one.
>
> @psychon that's sound good!

Well... I'm not pavouk. I can merge stuff here, but I cannot change any repo settings and I cannot even do releases. So... what would be the difference between a wiki and having a `doc/` folder with markdown files which can be edited through PRs?

**Comment by diazvictor** [comment]
> Okay, that was quick and quite positive. Nice. :-)
> 
> > > excellent contribution, I take this opportunity to comment on the possibility of a wiki.I would be willing to collaborate in the creation of this one.
> > 
> > 
> > @psychon that's sound good!
> 
> Well... I'm not pavouk. I can merge stuff here, but I cannot change any repo settings and I cannot even do releases. So... what would be the difference between a wiki and having a `doc/` folder with markdown files which can be edited through PRs?

well, discarding the wiki, the only thing left to do is to improve the current documentation.

**Comment by M1que4s** [comment]
> well, discarding the wiki, the only thing left to do is to improve the current documentation.

I am of the same opinion. Although they may just be small changes

**Pull request merged**
