### PR TITLE
Add support for indexing Gtk.TreeStore and Gtk.ListStore with nums or strs

### PR DESCRIPTION
**Pull request by v1993**
This patch enables indexing Gtk.TreeStore and Gtk.ListStore with numbers (e. g. `liststore[0]`) or strings (e.g. `treestore["1:2"]`). Usefull example: you got string from GtkComboBox, and want to give value from its ListStore, then it will be so easy:

    local active = MyComboBox:get_active()
    local row = MyListStore[active]
Should I provide tests for this feature?

### CODE REVIEW

**Comment by pavouk** [comment]
Feature and implementation looks good to me. Providing tests would be great, and also adding a few sentences describing the feature into docs/gtk.md.  However, even if you will not get to writing tests and/or docs, let me know and I will merge the feature as is.

**Comment by v1993** [comment]
I wrote some documentation for this patch, but testing system is too hard for me. You can merge.

**Comment by v1993** [comment]
I will *not* provide tests for it, so what about merge?

**Comment by psychon** [comment]
Since I never really used Gtk: Could you write some self-contained, runnable example that shows how/that this works? Basically what you wrote for the docs, but also including the necessary setup to make this code actually work/do something.

**Comment by v1993** [comment]
Check this out!

    local lgi = require 'lgi'
    local Gtk = lgi.Gtk
    local GObject = lgi.GObject
    
    local PersonColumn = { NAME = 1, AGE = 2, EMPLOYEE = 3 }
    
    local store = Gtk.ListStore.new {
    	[PersonColumn.NAME] = GObject.Type.STRING,
    	[PersonColumn.AGE] = GObject.Type.INT,
    	[PersonColumn.EMPLOYEE] = GObject.Type.BOOLEAN,
    }
    
    local person = store:append()
    store[person] = {
    	[PersonColumn.NAME] = "John Doe",
    	[PersonColumn.AGE] = 45,
    	[PersonColumn.EMPLOYEE] = true,
    }
    
    local person = store:append()
    store[person] = {
    	[PersonColumn.NAME] = "Valeri Ochinski",
    	[PersonColumn.AGE] = 15,
    	[PersonColumn.EMPLOYEE] = true,
    }
    
    local person = store:append()
    store[person] = {
    	[PersonColumn.NAME] = "Random man",
    	[PersonColumn.AGE] = 26,
    	[PersonColumn.EMPLOYEE] = false,
    }
    
    local combobox, renderer, info_label = Gtk.ComboBox.new_with_model(store), Gtk.CellRendererText()
    combobox:pack_start(renderer, true)
    combobox:add_attribute(renderer, 'text', 0)
    combobox.expand = true
    combobox.vexpand = false
    
    combobox.on_changed = function()
    	local row = store[combobox:get_active()] -- <--- New functional
    	info_label:set_text(string.format([[Age: %d
    Employee: %s]], row[PersonColumn.AGE], row[PersonColumn.EMPLOYEE] and 'yes' or 'no'))
    end
    
    info_label = Gtk.Label {
    	expand = true,
    	vexpand = false,
    }
    
    info_label:set_text 'Select item'
    info_label:set_lines(2)
    
    
    local window = Gtk.Window {
    	title = 'Application',
    	default_width = 640, default_height = 480,
    	Gtk.Grid {
    		orientation = Gtk.Orientation.VERTICAL,
    		Gtk.Toolbar {
    			Gtk.ToolButton { id = 'about', stock_id = Gtk.STOCK_ABOUT, on_clicked = function() print('No help for you') end },
    			Gtk.ToolButton { id = 'quit', stock_id = Gtk.STOCK_QUIT, on_clicked = Gtk.main_quit },
    		},
    		combobox,
    		info_label,
    		Gtk.Statusbar { id = 'statusbar' }
    	},
    	on_destroy = Gtk.main_quit
    }
    
    window:show_all()
    Gtk.main()

**Comment by v1993** [comment]
@psychon I did forgot to mention you.

**Comment by psychon** [comment]
Thanks!
And sorry that this took so long.

**Pull request merged**
