### PR TITLE
Add compress.lua example

### PR DESCRIPTION
**Pull request by v1993**
I've been struggling for a while with how to use converters, so I think that this example may help others later.

If you have any questions/ideas about it, I will be glad to help with improving.

### CODE REVIEW

**Comment by TingPing** [comment]
Maybe error handling would be a good idea.

**Comment by v1993** [comment]
@TingPing Well, I've already added checks which were required to produce meaningful errors during testing. Do you suggest to add `assert` on every single call which may fail in theory?

**Comment by TingPing** [comment]
Well, at a glance the `splice()` call is among the more important ones. For examples I'd also say `assert()`s are bad compared to printing the error messages.

**Comment by v1993** [comment]
@TingPing Ok about more checks, will do that. What do you have against `assert`, by the way? They still print error message to console (and exit to prevent further problems).

**Comment by psychon** [comment]
@TingPing Are you fine with this now?

**Comment by ildar** [comment]
Guys,  this is an example, not a production application. Excessive error
checks may only obscure it
IMHO

**Comment by TingPing** [comment]
I mean I'm not going to block it or anything. I just think examples should represent real usage and that means handling expected errors not asserting.

No big deal.

**Comment by psychon** [comment]
I'll count that as "reviewed by @TingPing" :-)

**Pull request merged**
